version: "3.8"
services:
  frontend:
    build:
      context: ./
      args:
        - REACT_APP_API_BASE_URL=$CLIENT_API_BASE_URL
    volumes:
      - ./:/frontend
      - frontend_deps:/frontend/node_modules
    ports:
      - 3000:3000

volumes:
  frontend_deps: {}
